"""create_accounts_and_account_shares_tables

Revision ID: 5ed7d2606ef9
Revises: f13dbedae659
Create Date: 2025-11-03 21:27:13.593196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed7d2606ef9'
down_revision: Union[str, Sequence[str], None] = 'f13dbedae659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.Enum('SAVINGS', 'CREDIT_CARD', 'DEBIT_CARD', 'LOAN', 'INVESTMENT', 'OTHER', name='accounttype'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_accounts_ck_accounts_currency_format')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_index(op.f('ix_accounts_account_name'), 'accounts', ['account_name'], unique=False)
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_accounts_created_at'), 'accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_accounts_created_by'), 'accounts', ['created_by'], unique=False)
    op.create_index(op.f('ix_accounts_currency'), 'accounts', ['currency'], unique=False)
    op.create_index(op.f('ix_accounts_deleted_at'), 'accounts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_is_active'), 'accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_accounts_updated_by'), 'accounts', ['updated_by'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)

    # Partial unique index: account names must be unique per user (case-insensitive)
    # WHERE deleted_at IS NULL allows reusing names after soft delete
    op.execute("""
        CREATE UNIQUE INDEX idx_accounts_user_name_unique
        ON accounts(user_id, LOWER(account_name))
        WHERE deleted_at IS NULL
    """)

    op.create_table('account_shares',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_level', sa.Enum('OWNER', 'EDITOR', 'VIEWER', name='permissionlevel'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_account_shares_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_account_shares_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_shares'))
    )
    op.create_index(op.f('ix_account_shares_account_id'), 'account_shares', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_shares_created_at'), 'account_shares', ['created_at'], unique=False)
    op.create_index(op.f('ix_account_shares_created_by'), 'account_shares', ['created_by'], unique=False)
    op.create_index(op.f('ix_account_shares_deleted_at'), 'account_shares', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_account_shares_id'), 'account_shares', ['id'], unique=False)
    op.create_index(op.f('ix_account_shares_permission_level'), 'account_shares', ['permission_level'], unique=False)
    op.create_index(op.f('ix_account_shares_updated_by'), 'account_shares', ['updated_by'], unique=False)
    op.create_index(op.f('ix_account_shares_user_id'), 'account_shares', ['user_id'], unique=False)

    # Composite index for permission lookups (most frequent query)
    # Optimizes: "Get user's permission for account"
    op.create_index(
        'idx_account_shares_permission_lookup',
        'account_shares',
        ['account_id', 'user_id', 'deleted_at']
    )

    # Partial unique index: one active share per user per account
    # WHERE deleted_at IS NULL allows re-sharing after revocation
    op.execute("""
        CREATE UNIQUE INDEX idx_account_shares_unique
        ON account_shares(account_id, user_id)
        WHERE deleted_at IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop custom indexes for account_shares
    op.execute("DROP INDEX IF EXISTS idx_account_shares_unique")
    op.execute("DROP INDEX IF EXISTS idx_account_shares_permission_lookup")

    op.drop_index(op.f('ix_account_shares_user_id'), table_name='account_shares')
    op.drop_index(op.f('ix_account_shares_updated_by'), table_name='account_shares')
    op.drop_index(op.f('ix_account_shares_permission_level'), table_name='account_shares')
    op.drop_index(op.f('ix_account_shares_id'), table_name='account_shares')
    op.drop_index(op.f('ix_account_shares_deleted_at'), table_name='account_shares')
    op.drop_index(op.f('ix_account_shares_created_by'), table_name='account_shares')
    op.drop_index(op.f('ix_account_shares_created_at'), table_name='account_shares')
    op.drop_index(op.f('ix_account_shares_account_id'), table_name='account_shares')
    op.drop_table('account_shares')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_updated_by'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_is_active'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_deleted_at'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_currency'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_created_by'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_created_at'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_name'), table_name='accounts')

    # Drop custom index for accounts
    op.execute("DROP INDEX IF EXISTS idx_accounts_user_name_unique")

    op.drop_table('accounts')

    # Drop ENUM types
    op.execute("DROP TYPE IF EXISTS accounttype")
    op.execute("DROP TYPE IF EXISTS permissionlevel")
    # ### end Alembic commands ###
